### ISSUE TITLE
Does not open at all

### ISSUE THREAD

**Issue by s-ol** [griffin-stewie/asciidoctor-preview#1]
Nothing happens when I toggle, except that a deprecation warning shows up:

```
Call ::getActiveTextEditor instead 
Workspace.getActiveEditor - /usr/share/atom/resources/app/src/workspace.js:999:12
Object.checkFile - /home/s0lll0s/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:107:28
```

**Comment by griffin-stewie** [comment]
@S0lll0s 
Can you tell me your 
- Atom Editor version 
- asciidoctor-preview version

**Comment by s-ol** [comment]
Both latest. On the phone ATM, but I installed atom from the AUR yesterday, so it's a really recent git build.

Alright, it's atom 0.190.0 and asciidoctor-preview 0.1.2.

**Comment by griffin-stewie** [comment]
@S0lll0s 
I released v0.1.3 now.
https://atom.io/packages/asciidoctor-preview

Can you try this ?

**Comment by s-ol** [comment]
Had a python3 related error with node-gyp during the installation, I fixed it with

```
apm config set python /usr/bin/python2.7
```

and it installed fine. However toggling still doesn't do anything (though the deprecation warning is gone now too).

**Comment by griffin-stewie** [comment]
Hmmm.
Can you send me logs when you toggling.

**Comment by s-ol** [comment]
```
/home/s0lll0s/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:110 AsciidoctorPreview was toggled!
```

Appears in the developer tools, that's everything that's happening.

**Comment by griffin-stewie** [comment]
It was reproduced!
I'm going to try to fix.

**Comment by griffin-stewie** [comment]
@S0lll0s 
I released v0.1.4.
Could you try it again with v0.1.4 ?

**Comment by s-ol** [comment]
still nothing at all happening :/

**Comment by griffin-stewie** [comment]
@S0lll0s 

hmmm. I don't know what's going on.

This package works adoc file which has extension "adoc".

Can you download file bellow and try ?

https://gist.githubusercontent.com/griffin-stewie/687ae8092ddd8066f41f/raw/57b6e4b4b7b64c7cc5f3059454bef83f58ca6555/sample.adoc

**Comment by s-ol** [comment]
Oh wait, It opens now after restarting atom. There currently is a "command not found" error, but thats my fault probably.

**Comment by griffin-stewie** [comment]
You mean, it may works fine ?
