### ISSUE TITLE
:toc: left shows misplaced table of contents

### ISSUE THREAD

**Issue by sluedecke** [griffin-stewie/asciidoctor-preview#10]
Whenever setting :toc: to left or right, there will be a stray display of the toc.

In the example it works out since it convers the tree view, but this is by chance.  The stray toc simply covers some some space on the Atom screen.

![screenshot1](https://cloud.githubusercontent.com/assets/7710530/11155735/aab42dce-8a47-11e5-8c40-9a0ec3ab23cf.png)

ADOC file: 

= Sample document
:toc: left

== Entry 1

Table of content is misplaced on the screen

**Comment by griffin-stewie** [comment]
@sluedecke 

Reproduced. I'm try to fix this soon, but I'm not good at HTML, CSS stuffs. I hope I could.

**Comment by griffin-stewie** [comment]
@sluedecke 
It was really long road. Finally this issue was fixed, and also TOC link jump works.
