### ISSUE TITLE
can't install successfull.

### ISSUE THREAD

**Issue by asktalk** [griffin-stewie/asciidoctor-preview#12]
C:\Users\xxx>apm install asciidoctor-preview
Installing asciidoctor-preview to C:\Users\asktalk.atom\packages failed

> runas@3.1.1 install C:\Users\asktalk\AppData\Local\Temp\apm-install-dir-1151129-11380-1ahl3cw\node_modules\asciidoctor-preview\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\asktalk\AppData\Local\Temp\apm-install-dir-1151129-11380-1ahl3cw\node_modules\asciidoctor-preview\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\asktalk\AppData\Local\atom\app-1.3.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\asktalk\AppData\Local\atom\app-1.3.2\resources\app\apm\bin\node.exe" "C:\Users\asktalk\AppData\Local\atom\app-1.3.2\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\asktalk\.atom\.apm\.apmrc" "--userconfig" "C:\Users\asktalk\.atom\.apmrc" "install" "C:\Users\asktalk\AppData\Local\Temp\d-1151129-11380-17hbrlu\package.tgz" "--target=0.34.3" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by griffin-stewie** [comment]
@asktalk 
This is runas package's issue. I can't help you out. Sorry about that.
