### ISSUE TITLE
Issue installing plugin through Atom

### ISSUE THREAD

**Issue by aleitner** [griffin-stewie/asciidoctor-preview#14]
I'm installing onto Windows 7 64bit Atom.
I go to Atom->Settings->Install. I search Asciidoc and click install on asciidoctor-preview, and I encounter the following error message.

> runas@3.1.1 install C:\Users\axl134\AppData\Local\Temp\apm-install-dir-116011-39668-1e6aaci\node_modules\asciidoctor-preview\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\axl134\AppData\Local\Temp\apm-install-dir-116011-39668-1e6aaci\node_modules\asciidoctor-preview\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\axl134\AppData\Local\atom\app-1.3.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\axl134\AppData\Local\atom\app-1.3.3\resources\app\apm\bin\node.exe" "C:\Users\axl134\AppData\Local\atom\app-1.3.3\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\axl134\.atom\.apm\.apmrc" "--userconfig" "C:\Users\axl134\.atom\.apmrc" "install" "C:\Users\axl134\AppData\Local\Temp\d-116011-39668-16p3j6v\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by griffin-stewie** [comment]
@aleitner 
I'm sorry that I cannot reproduce this issue because I don't have Windows.
This package does not support Windows environment.
