### ISSUE TITLE
version 0.1.7 failed to instal lon win7 64bit

### ISSUE THREAD

**Issue by dkotrada** [griffin-stewie/asciidoctor-preview#15]
Installing “asciidoctor-preview@0.1.7” failed.Hide output…

> runas@3.1.1 install C:\Users\vrcmr\AppData\Local\Temp\apm-install-dir-11618-5192-q1eq3n\node_modules\asciidoctor-preview\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

Der Befehl "node-gyp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\vrcmr\AppData\Local\atom\app-1.4.3\resources\app\apm\bin\node.exe" "C:\Users\vrcmr\AppData\Local\atom\app-1.4.3\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\vrcmr\.atom\.apm\.apmrc" "--userconfig" "C:\Users\vrcmr\.atom\.apmrc" "install" "C:\Users\vrcmr\AppData\Local\Temp\d-11618-5192-vahzl6\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by griffin-stewie** [comment]
@dkotrada 
I'm sorry that I cannot reproduce this issue because I don't have Windows.
This package does not support Windows environment.
