### ISSUE TITLE
asciidoctor preview in Atom fails to resolve any includes

### ISSUE THREAD

**Issue by PaulAnderson-One** [griffin-stewie/asciidoctor-preview#16]
commandline includes work with asciidoctor
asciidoc (note: no 'tor' at the end - this is just plain asciidoc) resolves the includes.

It is this way for every single adoc file I try. Overriding the setting in Atom Asciidoc-preview has no effect

**Comment by griffin-stewie** [comment]
@PaulAndersonMule 

Unfortunately, assciidoctor-preview does not support `includes` now. The reason is architecture. asciidoctor-preview copies current adoc file to temp directory to generate html5 and shows html5 document as Preview. I am not sure why I choose this architecture, but, that's why asciidoctor can not resolve `includes` path.

I want to fix this, but it is going to be tough.

**Comment by griffin-stewie** [comment]
@PaulAndersonMule 

I released v0.2.0. 
I hope that issue has been resolved.

Please make sure that settings. I changed parameters for asciidoctor command. now We need `--base-dir` (default value is dirname of preview adoc file.) I recommend reset your overrided command options and args.

**Comment by PaulAnderson-One** [comment]
@griffin-stewie the thumbs-up was a hopeful sign. I just tried this now and it fails with the error below. I have a workaround (I preview with asciidoc and when I'm close I asciidoctor it from the commandline (which can resolve includes etc.)

discoveryAgenda.adoc /usr/local/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:381:in `rescue in get_header': Failed to get header. (MentosError) from /usr/local/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:362:in`get_header' from /usr/local/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:259:in `block in mentos' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:91:in`block in timeout' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `block in catch' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:33:in`catch' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `catch' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:106:in`timeout' from /usr/local/lib/ruby/gems/2.3.0/gems/pygments.rb-

**Comment by PaulAnderson-One** [comment]
I just tried some variations: includes do resolve. There's something in this particular include that breaks - and it's this:

:source-highlighter: pygments
