### ISSUE TITLE
'asciidoctor-diagram' could not be loaded.

### ISSUE THREAD

**Issue by Jack-023** [griffin-stewie/asciidoctor-preview#18]
I just installed Asciidoctor for the first time and downloaded this extension to try it out so I guess this could be user error. Let me know either way.

I copied the test file from [Asciidoctor](http://asciidoctor.org/) and hit ctrl-shift-o and it came up with this error in the new window:

Previewing AsciiDoc Failed

`Command failed: /bin/sh -c asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram --base-dir /Users/myUser/Documents/Asciidocs -o /var/folders/wd/qfyk88gd37j8l99hcwd54l9w0000gn/T/asciidoctor11631-6927-19gitno/temp.html /Users/myUser/Documents/Asciidocs/test.adoc asciidoctor: FAILED: 'asciidoctor-diagram' could not be loaded Use --trace for backtrace`

**Comment by griffin-stewie** [comment]
@Jack-023 

You need [asciidoctor-diagram](http://asciidoctor.org/docs/asciidoctor-diagram/) by default.

If you would like to use [asciidoctor-diagram](http://asciidoctor.org/docs/asciidoctor-diagram/) , then install it.

If you don't need [asciidoctor-diagram](http://asciidoctor.org/docs/asciidoctor-diagram/) . You can change command like bellow

```
asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book --base-dir {{{baseDirPath}}} -o {{{tempHTMLPath}}} {{{filePath}}}
```

**Comment by Jack-023** [comment]
Thanks for the help!
