### ISSUE TITLE
Installation fails: Failed at the runas@3.1.1 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by simontite-capita-ti** [griffin-stewie/asciidoctor-preview#19]
<pre>
$ apm install asciidoctor-preview
Installing asciidoctor-preview to /home/simon/.atom/packages ✗

> runas@3.1.1 install /tmp/apm-install-dir-116315-11438-1ng661a/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas'
> node-gyp rebuild`

make: Entering directory '/tmp/apm-install-dir-116315-11438-1ng661a/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:90: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-116315-11438-1ng661a/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas/build'

npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
In file included from ../src/main.cc:1:0:
../../nan/nan.h:194:57: fatal error: nan_maybe_43_inl.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.6-300.fc23.x86_64
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-116315-11438-1ng661a/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Linux 4.4.6-300.fc23.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/simon/.atom/.apm/.apmrc" "--userconfig" "/home/simon/.atom/.apmrc" "install" "/tmp/d-116315-11438-10yg153/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116315-11438-1ng661a/npm-debug.log
$

The log file mentioned above doesn't exist, and there is no file *.log in the /tmp directory.
</pre>

**Comment by griffin-stewie** [comment]
@simontite-capita-ti 
Can you update to v0.2.1 ? I updated dependencies.

**Comment by simontite-capita-ti** [comment]
@griffin-stewie 
Thanks that installed fine.
