### ISSUE TITLE
temporary folder created in wrong place

### ISSUE THREAD

**Issue by s-ol** [griffin-stewie/asciidoctor-preview#2]
`asciidoctor-preview` puts a `tmp` directory in the working directory (`~` in my case), it should use `/tmp` instead.

**Comment by griffin-stewie** [comment]
@S0lll0s 
In my case, temp directory is located like this `/var/folders/xq/53ysyxjd02b2q9xlz0jgf2br0000gn/T/asciidoctor11548-7899-mzicgk`.
`asciidoctor-preview` uses temp directory to generate preview html file. I'm using `https://github.com/bruce/node-temp` library to make temp directory.

**Comment by s-ol** [comment]
for me it creates `~/tmp/asciidoctor11547-17506-1lnsgrv`. Arch 3.18, I'll see if I can test that libary on it's own. How are you invoking it?

**EDIT:** when I use `temp.track()` and `temp.mkdir()` things are stored in `/tmp` correctly. I am using temp 0.8.1.

**Comment by griffin-stewie** [comment]
I'm using `temp` library version 0.6.0, and latest version is 0.8.1. Maybe I should update version of `temp` .

**Comment by griffin-stewie** [comment]
I released v0.1.5.

**Comment by s-ol** [comment]
Great, I'll try it in The afternoon.

**Comment by s-ol** [comment]
Seems to be working.

**Comment by griffin-stewie** [comment]
cool
