### ISSUE TITLE
Error updating Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by ArthurZ** [griffin-stewie/asciidoctor-preview#20]
Uncaught TypeError: Cannot read property 'substr' of null
/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:709
Show Stack Trace
The error was thrown from the settings-view package. This issue has already been reported.

**Comment by griffin-stewie** [comment]
@ArthurZ 
Thx
