### ISSUE TITLE
v 0.2.1error message in preview pane, file not found.

### ISSUE THREAD

**Issue by simontite-capita-ti** [griffin-stewie/asciidoctor-preview#21]
This is the result when the preview is toggled on:
`Previewing AsciiDoc Failed`

`Command failed: /bin/sh -c "asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram --base-dir /home/simon/d/adoc -o /tmp/asciidoctor11649-5956-1joyird/temp.html /home/simon/d/adoc/My notes.adoc" -l /bin/sh: asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram --base-dir /home/simon/d/adoc -o /tmp/asciidoctor11649-5956-1joyird/temp.html /home/simon/d/adoc/My notes.adoc: No such file or directory`

In the temporary output directory `/tmp/asciidoctor11649-5956-1joyird/` there is no file `temp.html`, although there _is_ a copy of `"My notes.adoc"`.

This issue seems similar to issue #18, but I _have_ installed asciidoctor-diagram.

**Comment by griffin-stewie** [comment]
@simontite-capita-ti 
Can you try AsciiDoc file name `My notes.adoc` to `my_notes.adoc`. I mean no space in file name.

**Comment by simontite-capita-ti** [comment]
@griffin-stewie 
Tried that, the message is the same, ending `/home/simon/d/adoc/MyNotes.adoc: No such file or directory`.

**Comment by simontite-capita-ti** [comment]
@griffin-stewie 
I'm thinking, asciidoctor-diagram doesn't appear in my PATH.  That is I get:
`[simon@simdell ~]$ which asciidoctor`
`~/bin/asciidoctor`
`[simon@simdell ~]$`

which is ok, but
`[simon@simdell ~]$ which asciidoctor-diagram`
`/usr/bin/which: no asciidoctor-diagram in (/home/simon/ansible/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/simon/p/ec2/ec2-api-tools-1.7.1.2/bin:/home/simon/.local/bin:/home/simon/bin:/u:/home/simon/p/ec2/ec2-api-tools-1.7.1.2/bin)`

which is probably not ok?
There is a  `~/.gem/.ruby/gems/asciidoctor-diagram-1.4.0` directory, but no executable files. 

Tried a symbolic link from `~\bin\asciidoctor-diagram -> ~/.gem/ruby/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram.rb`, but no luck there.

**Comment by griffin-stewie** [comment]
@simontite-capita-ti 
I think asciidoctor-diagram is not failure reason.
#18 that you point at, it has error message like

```
FAILED: 'asciidoctor-diagram' could not be loaded Use --trace for backtrace
```

This was point of #18 probrem, but your case does not.

Can you run this command bellow ?

``` sh
asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram --base-dir /home/simon/d/adoc -o /tmp/asciidoctor11649-5956-1joyird/temp.html /home/simon/d/adoc/MyNotes
```

I want to make sure, you can run it from terminal OR not.
If you could good results when you run from terminal, then my package has some problem. If NOT, then you have to resolve asciidoctor issues.

**Comment by simontite-capita-ti** [comment]
@griffin-stewie 

That didn't work at first with file name "MyNotes" but it worked ok with filename "MyNotes.adoc".

**Comment by griffin-stewie** [comment]
@simontite-capita-ti 
Alright, so it seems 'asciidoctor-preview' has some issue.
The point is `No such file or directory` means, which file does not exits.
Could you give me following informations?
- OS
- Atom Editor's version
- asciidoctor-preview package's version
  - you already told me v0.2.1. lol
- asciidoctor's version

**Comment by simontite-capita-ti** [comment]
@griffin-stewie 
- OS: Fedora 23
- Atom 1.7.1
- asciidoctor-preview, yes, v0.2.1 I think. (Is there a way of verifying that?)
- Asciidoctor v 1.5.4

**Comment by griffin-stewie** [comment]
@simontite-capita-ti 
I prepared Fedora 23 environment on my Mac via VirtualBox. However I could not reproduce this issue.
Unfortunately I can not fix this issue.
