### ISSUE TITLE
asciidoctor preview broken for anything with includes

### ISSUE THREAD

**Issue by PaulAnderson-One** [griffin-stewie/asciidoctor-preview#23]
version 0.3.0 updated minutes ago

Previewing AsciiDoc Failed

Command failed: /bin/sh -c asciidoctor --trace --safe-mode unsafe -a lang=en -b html5 -d book --base-dir /Users/xx/yy/zz -o /var/folders/45/jc7tm14n6jlbww0qz8q_pgmm0000gp/T/asciidoctor116513-75877-1a8epyv/temp.html /xx/yy/zz/README.adoc /usr/local/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:381:in `rescue in get_header': Failed to get header. (MentosError) from /usr/local/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:362:in`get_header' from /usr/local/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:259:in `block in mentos' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:91:in`block in timeout' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `block in catch' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:33:in`catch' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `catch' from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:106:in`timeout' from /usr/local/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:233:in `mentos' from /usr/local/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:178:in`css' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/stylesheets.rb:74:in `pygments_stylesheet_data' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/stylesheets.rb:82:in`embed_pygments_stylesheet' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/html5.rb:99:in `document' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/base.rb:34:in`convert' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044:in `convert' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503:in`convert' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in`each' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `invoke!' from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.4/bin/asciidoctor:14:in`<top (required)>' from /usr/local/bin/asciidoctor:23:in `load' from /usr/local/bin/asciidoctor:23:in`<main>'

**Comment by griffin-stewie** [comment]
@PaulAndersonMule 
These are Ruby stuff. I can't handle of this, sorry about that.
