### ISSUE TITLE
preview height size

### ISSUE THREAD

**Issue by gtortone** [griffin-stewie/asciidoctor-preview#27]
Hi,
if I preview my asciidoc the windows height is "compressed" at top:

![asciidoctor-preview](https://cloud.githubusercontent.com/assets/6534590/18416201/6084d730-780d-11e6-87f6-feb141c00556.png)

**Comment by PaulAnderson-One** [comment]
Hi, I too see that bug

**Comment by griffin-stewie** [comment]
@gtortone  @PaulAndersonMule 
I could reproduced this issue.
I'm going to try to fix this soon.

**Comment by ali-gs** [comment]
I was just going to add this one as another issue but found this issue on the top  :)

**Comment by ali-gs** [comment]
@griffin-stewie  Is there any work-around or would need to wait for the fix?

**Comment by griffin-stewie** [comment]
@ali-gs 
Currently I have no idea, but I am going to try to fix this.

**Comment by griffin-stewie** [comment]
@gtortone @PaulAndersonMule @ali-gs
Hi, guys
I released v0.3.1 that fixed this issue.

**Comment by gtortone** [comment]
It works !

Thanks a lot !

**Comment by ali-gs** [comment]
@griffin-stewie I check its fixed Thanks. I had to restart the atom
