### ISSUE TITLE
Support without Asciidoctor

### ISSUE THREAD

**Issue by jeffeb3** [griffin-stewie/asciidoctor-preview#3]
I don't have Asciidoctor, but I do have Asciidoc.

Maybe you could change the interface to allow people to use asciidoc instead?

I managed to get this to work by changing the command to:
asciidoc -b html5 -d book -a lang=ja -o {{{tempHTMLPath}}} {{{tempSourcePath}}}

This should at least be documented, although I think it would make more sense as a well defined option in the settings. Maybe the command line option should be [Asciidoctor defaults, Asciidoc defaults, custom (with box)]

**Comment by griffin-stewie** [comment]
@jeffeb3 
Yes, It's my intended use case.
I came up with asciidoctor-preview when I use [Marked 2](http://marked2app.com/).

I am going to add note about this usage.
