### ISSUE TITLE
asciidoctor-preview plugin for Atom shows messy code

### ISSUE THREAD

**Issue by lioupayphone** [griffin-stewie/asciidoctor-preview#34]
Atom 1.15 on Windows 10 x64 Pro

![image](https://cloud.githubusercontent.com/assets/7641944/24837220/8464b176-1d61-11e7-9029-d3c686bef91d.png)

But if I execute the command to generate xx.html and preview it with a browser, it seems everything ok.

![image](https://cloud.githubusercontent.com/assets/7641944/24837243/26832c26-1d62-11e7-911f-e1fcea9249a8.png)

**Comment by lioupayphone** [comment]
The version of asciidoctor-preview plugin is 0.3.2

**Comment by griffin-stewie** [comment]
@lioupayphone 
Maybe same issue this.
https://github.com/griffin-stewie/asciidoctor-preview/issues/7#issuecomment-133817298

**Comment by lioupayphone** [comment]
@griffin-stewie

Not related with #7.  :-(
![image](https://cloud.githubusercontent.com/assets/7641944/24941490/7fb2a8cc-1f7d-11e7-81e8-eea5cd121b84.png)

**Comment by lioupayphone** [comment]
ugly work around:

- hardcode the absolute path of asciidoctor (Say  C:\Ruby23-x64\bin\asciidoctor) in asciidoctor-preview.coffee and asciidoctor-preview-view.coffee
- hardcode the java (Say C:\Program Files (x86)\Java\jdk1.8.0_121\bin\java.exe) in java_socket.rb
```
      def self.registry_current(key)
        current_version = registry_query(key, 'CurrentVersion')
        if current_version
          java_home = registry_query("#{key}\\#{current_version}", 'JavaHome')
          java_exe(java_home)
        else
          java_home = 'C:\\Program Files (x86)\\Java\\jre1.8.0_121\\'
		  java_exe(java_home)
        end
      end
```

I don't know why this plugin has so many bugs on Windows(Atom). But it seems the workaround works. :-(

**Comment by lioupayphone** [comment]
As a matter of fact, this bug is caused by wrong ENV variables. I don't understand Ruby and .coffee. But I guess this plugin and asciidoctor-diagram failed to process path string and ENV with a proper manner on Microsoft Windows.

**Comment by lioupayphone** [comment]
@griffin-stewie 

You can close this issue, even though no patch can be submitted to get it resolved completed. :-(

**Comment by griffin-stewie** [comment]
@lioupayphone 

> I don't know why this plugin has so many bugs on Windows(Atom).

The reason is simple, I am not going to support it, cause I don't have Windows. I'm sorry for inconvenience.

**Comment by lioupayphone** [comment]
ok, I switch from Microsoft Windows to Apple MacBook Pro... Then I can get supported? :-)

**Comment by griffin-stewie** [comment]
I can help you as much as I can if you use latest macOS.
