### ISSUE TITLE
Diagram and math expression not displayed correctly

### ISSUE THREAD

**Issue by yeduzhouzi** [griffin-stewie/asciidoctor-preview#37]
![_20170706141337](https://user-images.githubusercontent.com/16047070/27910490-b15636d0-6255-11e7-9069-571578143b0a.png)
As shown in the picture, neither the math expression nor the diagram can be displayed correctly, yet I have installed all the environment needed including the asciidoctor-diagram. If I copy the command like `asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram --base-dir D:\atom -o C:\Users\DengZ1\AppData\Local\Temp\asciidoctor11766-15476-1ux1bii.30cvzn0zfr\temp.html` to the command line and run it, I will get a html file successfully and it displays everything well if opened with a browser, so I suppose I missed something with the PATH configuration? Right now it's `C:\Ruby24-x64\bin`.

I use windows and I installed asciidoctor along with asciidoctor-diagram with the command `gem` .

**Comment by griffin-stewie** [comment]
I am sorry but I can only support macOS.
