### ISSUE TITLE
the asciidoctor execute error.

### ISSUE THREAD

**Issue by hachi-kun** [griffin-stewie/asciidoctor-preview#38]
the asciidoctor occur error to exec its command when the asciidoc docmet with plantuml/mermaid preview by asciidoctor-preview.

using system :
os                  : ubuntu 16.04
asciidoctor         : 1.5.6.1
asciidoctor-diagram : 1.5.5

I exec command which is used by default of asciidoctor-preview by console. so, the error occur error which is EIDIR. 

> % asciidoctor --trace -a lang=ja -b html5 -d book -r asciidoctor-diagram --base-dir /home/katsumi /tmp/plantuml -o /tmp/asciidoctor11791-3169-1gct4g5.ieh15lv7vi/trmp.html /home/katsumi/tmp/plantuml/test.adoc 
/home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1092:in `write': Is a directory @ rb_sysopen - /tmp/asciidoctor11791-3169-1gct4g5.ieh15lv7vi/trmp.html (Errno::EISDIR)
	from /home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1092:in `write'
	from /home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1507:in `convert'
	from /home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `block in convert_file'
	from /home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `open'
	from /home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `convert_file'
	from /home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:108:in `block in invoke!'
	from /home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `each'
	from /home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `invoke!'
	from /home/katsumi/.gem/ruby/2.3.0/gems/asciidoctor-1.5.6.1/bin/asciidoctor:14:in `<top (required)>'
	from /usr/local/bin/asciidoctor:23:in `load'
	from /usr/local/bin/asciidoctor:23:in `<main>'

I change few command option for asciidoctor. so it not occur covert error. 
and the asciidoctor is complete to covert form asciidoc to html document 

> % asciidoctor --trace -a lang=ja -b html5 -d book -r asciidoctor-diagram -o temp.html -D /tmp/asciidoctor11791-3169-1gct4g5.ieh15lv7vi /home/katsumi/tmp/plantuml/test.adoc 

I feel that Is the asciidoctor or asciidoctor-diagram argument was changing specification.

I generate simple patch. Would you see it.

[diff.txt](https://github.com/griffin-stewie/asciidoctor-preview/files/1347225/diff.txt)

**Comment by griffin-stewie** [comment]
I am sorry but I can only support macOS.
