### ISSUE TITLE
Unable to install Asciidoctor Preview through Atom

### ISSUE THREAD

**Issue by jaredmorgs** [griffin-stewie/asciidoctor-preview#5]
I am attempting to install the package through Atom, and it is coming up with a fail.

> runas@2.0.0 install /tmp/apm-install-dir-115431-12262-1ewv1g4/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-115431-12262-1ewv1g4/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:88: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-115431-12262-1ewv1g4/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas/build'

make: g++: Command not found
make: **\* [Release/obj.target/runas/src/main.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.17.4-301.fc21.x86_64
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115431-12262-1ewv1g4/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.17.4-301.fc21.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/jmorgan/.atom/.apm/.apmrc" "--userconfig" "/home/jmorgan/.atom/.apmrc" "install" "/tmp/d-115431-12262-1475ph8/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115431-12262-1ewv1g4/npm-debug.log

**Comment by jaredmorgs** [comment]
I manually installed the latest release to the ~/.atom/packages directory and received this error when starting the app.

Cannot find module `fs-plus`. I've newly installed atom and fedora 21. 

I was going to demo this on Tuesday this week, but might have to just leave this for now until it starts working again.

> runas@2.0.0 install /tmp/apm-install-dir-115431-12262-1ewv1g4/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-115431-12262-1ewv1g4/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:88: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-115431-12262-1ewv1g4/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas/build'

make: g++: Command not found
make: **\* [Release/obj.target/runas/src/main.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.17.4-301.fc21.x86_64
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115431-12262-1ewv1g4/node_modules/asciidoctor-preview/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.17.4-301.fc21.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/jmorgan/.atom/.apm/.apmrc" "--userconfig" "/home/jmorgan/.atom/.apmrc" "install" "/tmp/d-115431-12262-1475ph8/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115431-12262-1ewv1g4/npm-debug.log

**Comment by griffin-stewie** [comment]
It seems node.js (npm) problem for me.
Can you install dependency libraries that asciidoctor-preview is using via npm ?

```
      "atom-space-pen-views": "^2.0.5",
      "fs-plus": "^2.5.0",
      "grim": "^1.4.0",
      "pathwatcher": "^4.4.0",
      "temp": "^0.8.1",
      "fs-extra": "^0.18.3",
      "underscore-plus": "^1.6.6",
      "wrench": "^1.5.8",
      "mustache": "^2.0.0",
      "cheerio": "^0.19.0"
```

**Comment by jaredmorgs** [comment]
Just as a follow-up to this, I installed asciidoc-preview to work around
the issue. I was actually after this package, but thought Asciidoctor
Preview was the canonical package provided by Asciidoctor.

On Sun, 31 May 2015 at 21:23 griffin-stewie notifications@github.com
wrote:

> It seems node.js (npm) problem for me.
> Can you install dependency libraries that asciidoctor-preview is using via
> npm ?
> 
> ```
>   "atom-space-pen-views": "^2.0.5",
>   "fs-plus": "^2.5.0",
>   "grim": "^1.4.0",
>   "pathwatcher": "^4.4.0",
>   "temp": "^0.8.1",
>   "fs-extra": "^0.18.3",
>   "underscore-plus": "^1.6.6",
>   "wrench": "^1.5.8",
>   "mustache": "^2.0.0",
>   "cheerio": "^0.19.0"
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/griffin-stewie/asciidoctor-preview/issues/5#issuecomment-107157736
> .
> 
> ## 

Sent from Mobile.

**Comment by griffin-stewie** [comment]
I can't reproduce this issue, sorry about that.
