### ISSUE TITLE
Previewing AsciiDoc Failed (Mas OS 10.10.4)

### ISSUE THREAD

**Issue by abhayghatpande** [griffin-stewie/asciidoctor-preview#7]
Path to asciidoctor executable is set in package preferences. The path to source file mentioned below exists. Cannot figure out which file is missing. I receive the following error:

```
Command failed: /bin/sh -c asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram -o /var/folders/qz/5450zhp94sxd5gr5nfz00qr00000gn/T/asciidoctor115721-24286-q3lvyd/temp.html /var/folders/qz/5450zhp94sxd5gr5nfz00qr00000gn/T/asciidoctor115721-24286-q3lvyd/InternshipReport.adoc env: bash: No such file or directory
```

The command works at the command line, if I supply the temp.html and .adoc file.

**Comment by griffin-stewie** [comment]
@abhayghatpande 

I think the reason is you didn't set PATH that you need. asciidoctor-preview has two prefs `Command` and `PATH`. I set `PATH` like bellow to use asciidoctor and gems.

```
/Users/Stewie/.rbenv/versions/2.2.2/bin:/Users/Stewie/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0:/usr/local/bin
```

**Comment by abhayghatpande** [comment]
@griffin-stewie 

Thanks for the reply. The problem was that the path was set to the `shims` path, `~/.rbenv/shims`. Probably it was not able to resolve to the actual executable in the bin directory. As per your suggestion, I changed the PATH to the actual bin directory and then it works! I didn't need the path to the ruby gems.
