### ISSUE TITLE
asciidoctor not found

### ISSUE THREAD

**Issue by sagarbehere** [griffin-stewie/asciidoctor-preview#8]
Hi,

I just installed asciidoctor-preview and it just refuses to find my asciidoctor binary.

I run ruby+asciidoctor in rbenv, and my $PATH is set up correctly, such that I can just fire up a terminal and type asciidoctor and it works. I tried the following:
1. Under Settings, edited PATH to /home/sagar/.rbenv/shims (the directory where asciidoctor binary is located)
2. Under Settings, tried to change the command to /home/sagar/.rbenv/shims/asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram -o {{{tempHTMLPath}}} {{{tempSourcePath}}}

Nothing works. The live preview says:

```
Previewing AsciiDoc Failed

Command failed: /bin/sh -c asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram -o /tmp/asciidoctor115726-30810-jzbp1v/temp.html /tmp/asciidoctor115726-30810-jzbp1v/platforms.adoc /bin/sh: 1: asciidoctor: not found
```

The funny thing is, if I copy/past the initial `/bin/sh -c asciidoctor` from the error message into a terminal window, the asciidoctor is found alright.

UPDATE: I was able to solve this by pasting the contents of my $PATH variable under Settings->PATH and simultaneously making the rbenv environment under which I'm running asciidoctor as the global system ruby environment. It would be really good to not have to do the latter (setting the global ruby environment).

**Comment by griffin-stewie** [comment]
@sagarbehere 
I'm using rbenv as well. For reference I'm going to show you my setting.
- `Settins->Command`
  - Default 
- `Settins->PATH`
  - `/Users/Stewie/.rbenv/versions/2.2.2/bin:/Users/Stewie/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0:/usr/local/bin`

thx
